services:
  - type: web
    name: ibei-church-site
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
